### ISSUE TITLE
Wrong Information in REST API for FOSSASIA 2017 Summit

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-orga-server#3238]
API end point : `https://eventyay.com/api/v1/events/6`

 - [ ]  Correct the copyright licence from `Attribution` to `Creative Commons Attribution License.`
      Issue : https://github.com/fossasia/open-event-webapp/issues/1063
 - [x]  Correct the Ticket URL from `https://eventyay.com/e/45da88b7/tickets/` to `https://eventyay.com/e/45da88b7/` 
     Issue: https://github.com/fossasia/open-event-webapp/issues/1067
@niranjan94 @SaptakS  Please help regarding this.

**Comment by poush** [comment]
@niranjan94 #3239 partially fixes this issue. First part is yet to be solved.

**Comment by aayusharora** [comment]
@niranjan94 @poush It seems that the ticket URL is corrected in the PR. I am in doubt why the API end point ` https://eventyay.com/api/v1/events/6` still provides wrong Ticket URL. Please confirm.

**Comment by poush** [comment]
Actually the ticket url is stored on the database and last PR fixed the process to store correct url on database. So the url you are receiving is coming directly from database. I think updating the event through wizard will fix this.

**Comment by niranjan94** [comment]
@aayusharora this PR has still not be deployed into the eventyay server. The URL will get updated once it is deployed and event get's updated. 

Deployment will be done in a few hours.

**Comment by aayusharora** [comment]
I don't know why it is closed. @niranjan94 please check if both the mentioned points are covered.
` Correct the copyright licence from Attribution to Creative Commons Attribution License.
Issue : fossasia/open-event-webapp#1063`
Please recheck this one.

**Comment by niranjan94** [comment]
@aayusharora sorry ... the closing was accidental .. Pressed the wrong comment button :sweat_smile:

**Comment by aayusharora** [comment]
@poush Any updates with this.

**Comment by Himanshi-Khandelwal** [comment]
@niranjan94 @aayusharora is this issue solved? When I checked the licence is already updated.

**Comment by shubham-padia** [comment]
Will add a new api field `licence` with every detail of the licence.
